name: cantina
description: "encomendas da cantina."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  firebase_messaging: ^15.2.5
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/comida.png
   - assets/comida2.jpg
   - assets/food.png
   - assets/food2.png
   - assets/estabelecimentos.png
   - assets/isutc.png
  
