// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63S991j0EGbNV3QjABvlh4GbDve1Ey38',
    appId: '1:739064472610:web:f2f60d246569f87069967b',
    messagingSenderId: '739064472610',
    projectId: 'cantina-5aa5d',
    authDomain: 'cantina-5aa5d.firebaseapp.com',
    storageBucket: 'cantina-5aa5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JMbAzkEVnIIpovfH6zyaGSX35NnvMuY',
    appId: '1:739064472610:android:af9671c3c54b5c8e69967b',
    messagingSenderId: '739064472610',
    projectId: 'cantina-5aa5d',
    storageBucket: 'cantina-5aa5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEsvx0xY_2SWOy9NJAySeMT6KnhGYkiA',
    appId: '1:739064472610:ios:4e25bd501291d1eb69967b',
    messagingSenderId: '739064472610',
    projectId: 'cantina-5aa5d',
    storageBucket: 'cantina-5aa5d.firebasestorage.app',
    iosBundleId: 'isutc.ac.mz.cantina',
  );
}
